# Jekyll configuration

permalink: date
pygments: true
exclude: ['Rakefile', 'README.md', 'config.rb', 'Gemfile', 'Gemfile.lock']
markdown: rdiscount
destination: public

# Configuration required for some pages

domain: blog.example.com
title: My Blog Title
author: Me
email: me@example.com

# Configuration for ehancements, uncomment to enable

# google_analytics:
#   account: UA-XXXXX-X

# github:
#   username: ghusername

# disqus:
#   id: disqusid
